<style>
    .bizum-message {
        background: #f7f7f7;
        margin: auto;
        margin-top: 40px;
        padding: 40px 24px 40px;
        color: #666;
        text-align: center;
        width: 100%;
        max-width: 480px;
        font-family: "Open Sans", Hevetica, Arial;
    }
</style>

<form action="<?php echo $this->getEnvironment(); ?>" method="post" id="bizum_form" name="bizum_form">
    <input type="hidden" name="Ds_SignatureVersion" value="<?php echo $this->getSignatureVersion(); ?>" />
    <input type="hidden" name="Ds_MerchantParameters" value="<?php echo $this->getParameters();  ?>" />
    <input type="hidden" name="Ds_Signature" value="<?php echo $this->getSignature(); ?>" />
</form>

<div class="bizum-message">
    <h4><?php echo __("Redirecting to Bizum PSP... Please wait."); ?></h4>
    <p><?php echo __("Thanks for trusting us. In a few seconds you will be redirected to the payment platform."); ?></p>
    <p><?php echo __("If your browser does not redirect you automatically click <a href='javascript:void(0)' onclick='document.bizum_form.submit();'>here</a> to carry out the payment."); ?></p>
</div>
<script type="text/javascript">
    document.bizum_form.submit();
</script>
